export const COROUSEL = {
    LOAD: "REQUEST_COROUSEL_DATA",
    LOAD_SUCCESS: "RECEIVE_COROUSEL_DATA",
  };

  export const TRENDINGCATEGORIES = {
  LOAD: "REQUEST_TRENDINGCATEGORIES_DATA",
  LOAD_SUCCESS: "RECEIVE_TRENDINGCATEGORIES_DATA",
};

